language: node_js

node_js:
  - '9'

cache:
  directories:
    - node_modules

script:
  - npm run build

after_script:
  - cd dist
  - git init
  - git config user.name 'zhuweiyou'
  - git config user.email 'i@zhuweiyou.com'
  - git add .
  - git commit -m '自动部署'
  - git push https://${GH_TOKEN}@github.com/zhuweiyou/zhuweiyou.com.git master:gh-pages -f

branches:
  only:
    - master
    - /^greenkeeper/.*$/
